using Ryujinx.Horizon.Common;
using Ryujinx.Horizon.Pctl.Types;
using Ryujinx.Horizon.Sdk.Sf;
using System;
using TimeSpan = Ryujinx.Horizon.Pctl.Types.TimeSpan;

namespace Ryujinx.Horizon.Sdk.Pctl
{
    internal interface IPctlService : IServiceObject
    {
        Result Initialize();
        Result CheckFreeCommunicationPermission();
        Result ConfirmLaunchApplicationPermission(ApplicationId applicationId, ReadOnlySpan<sbyte> arg1, bool arg2);
        Result ConfirmResumeApplicationPermission(ApplicationId applicationId, ReadOnlySpan<sbyte> arg1, bool arg2);
        Result ConfirmSnsPostPermission();
        Result ConfirmSystemSettingsPermission();
        Result IsRestrictionTemporaryUnlocked(out bool arg0);
        Result RevertRestrictionTemporaryUnlocked();
        Result EnterRestrictedSystemSettings();
        Result LeaveRestrictedSystemSettings();
        Result IsRestrictedSystemSettingsEntered(out bool arg0);
        Result RevertRestrictedSystemSettingsEntered();
        Result GetRestrictedFeatures(out int arg0);
        Result ConfirmStereoVisionPermission();
        Result ConfirmPlayableApplicationVideoOld(ReadOnlySpan<sbyte> arg0);
        Result ConfirmPlayableApplicationVideo(ApplicationId arg0, ReadOnlySpan<sbyte> arg1);
        Result ConfirmShowNewsPermission(ReadOnlySpan<sbyte> arg0);
        Result EndFreeCommunication();
        Result IsFreeCommunicationAvailable();
        Result IsRestrictionEnabled(out bool arg0);
        Result GetSafetyLevel(out int arg0);
        Result SetSafetyLevel(int arg0);
        Result GetSafetyLevelSettings(out RestrictionSettings restrictionSettings, int arg1);
        Result GetCurrentSettings(out RestrictionSettings restrictionSettings);
        Result SetCustomSafetyLevelSettings(RestrictionSettings restrictionSettings);
        Result GetDefaultRatingOrganization(out int arg0);
        Result SetDefaultRatingOrganization(int arg0);
        Result GetFreeCommunicationApplicationListCount(out int arg0);
        Result AddToFreeCommunicationApplicationList(ApplicationId arg0);
        Result DeleteSettings();
        Result GetFreeCommunicationApplicationList(out int arg0, Span<FreeCommunicationApplicationInfo> arg1, int arg2);
        Result UpdateFreeCommunicationApplicationList(ReadOnlySpan<FreeCommunicationApplicationInfo> arg0);
        Result DisableFeaturesForReset();
        Result NotifyApplicationDownloadStarted(ApplicationId applicationId);
        Result NotifyNetworkProfileCreated();
        Result ResetFreeCommunicationApplicationList();
        Result ConfirmStereoVisionRestrictionConfigurable();
        Result GetStereoVisionRestriction(out bool arg0);
        Result SetStereoVisionRestriction(bool arg0);
        Result ResetConfirmedStereoVisionPermission();
        Result IsStereoVisionPermitted(out bool arg0);
        Result UnlockRestrictionTemporarily(ReadOnlySpan<sbyte> arg0);
        Result UnlockSystemSettingsRestriction(ReadOnlySpan<sbyte> arg0);
        Result SetPinCode(ReadOnlySpan<sbyte> arg0);
        Result GenerateInquiryCode(out InquiryCode inquiryCode);
        Result CheckMasterKey(out bool arg0, InquiryCode inquiryCode, ReadOnlySpan<sbyte> arg2);
        Result GetPinCodeLength(out int arg0);
        Result GetPinCodeChangedEvent(out int arg0);
        Result GetPinCode(out int arg0, Span<sbyte> arg1);
        Result IsPairingActive(out bool arg0);
        Result GetSettingsLastUpdated(out PosixTime posixTime);
        Result GetPairingAccountInfo(out PairingAccountInfoBase pairingAccountInfo, PairingInfoBase pairingInfo);
        Result GetAccountNickname(out uint arg0, Span<sbyte> arg1, PairingAccountInfoBase arg2);
        Result GetAccountState(out int arg0, PairingAccountInfoBase pairingAccountInfo);
        Result RequestPostEvents(out int arg0, Span<EventData> arg1);
        Result GetPostEventInterval(out int arg0);
        Result SetPostEventInterval(int arg0);
        Result GetSynchronizationEvent(out int arg0);
        Result StartPlayTimer();
        Result StopPlayTimer();
        Result IsPlayTimerEnabled(out bool arg0);
        Result GetPlayTimerRemainingTime(out TimeSpan timeSpan);
        Result IsRestrictedByPlayTimer(out bool arg0);
        Result GetPlayTimerSettings(out PlayTimerSettings playTimerSettings);
        Result GetPlayTimerEventToRequestSuspension(out int arg0);
        Result IsPlayTimerAlarmDisabled(out bool arg0);
        Result NotifyWrongPinCodeInputManyTimes();
        Result CancelNetworkRequest();
        Result GetUnlinkedEvent(out int arg0);
        Result ClearUnlinkedEvent();
        Result DisableAllFeatures(out bool arg0);
        Result PostEnableAllFeatures(out bool arg0);
        Result IsAllFeaturesDisabled(out bool arg0, out bool arg1);
        Result DeleteFromFreeCommunicationApplicationListForDebug(ApplicationId applicationId);
        Result ClearFreeCommunicationApplicationListForDebug();
        Result GetExemptApplicationListCountForDebug(out int arg0);
        Result GetExemptApplicationListForDebug(out int arg0, Span<ExemptApplicationInfo> arg1, int arg2);
        Result UpdateExemptApplicationListForDebug(ReadOnlySpan<ExemptApplicationInfo> arg0);
        Result AddToExemptApplicationListForDebug(ApplicationId applicationId);
        Result DeleteFromExemptApplicationListForDebug(ApplicationId applicationId);
        Result ClearExemptApplicationListForDebug();
        Result DeletePairing();
        Result SetPlayTimerSettingsForDebug(PlayTimerSettings playTimerSettings);
        Result GetPlayTimerSpentTimeForTest(out TimeSpan timeSpan);
        Result SetPlayTimerAlarmDisabledForDebug(bool arg0);
        Result RequestPairingAsync(out AsyncData asyncData, out int arg1, ReadOnlySpan<sbyte> arg2);
        Result FinishRequestPairing(out PairingInfoBase pairingInfo, AsyncData asyncData);
        Result AuthorizePairingAsync(out AsyncData asyncData, out int arg1, PairingInfoBase pairingInfo);
        Result FinishAuthorizePairing(out PairingInfoBase pairingInfo, AsyncData asyncData);
        Result RetrievePairingInfoAsync(out AsyncData asyncData, out int arg1);
        Result FinishRetrievePairingInfo(out PairingInfoBase pairingInfo, AsyncData asyncData);
        Result UnlinkPairingAsync(out AsyncData asyncData, out int arg1, bool arg2);
        Result FinishUnlinkPairing(AsyncData asyncData, bool arg1);
        Result GetAccountMiiImageAsync(out AsyncData asyncData, out int arg1, out uint arg2, Span<byte> arg3, PairingAccountInfoBase arg4);
        Result FinishGetAccountMiiImage(out uint arg0, Span<byte> arg1, AsyncData arg2);
        Result GetAccountMiiImageContentTypeAsync(out AsyncData asyncData, out int arg1, out uint arg2, Span<sbyte> arg3, PairingAccountInfoBase arg4);
        Result FinishGetAccountMiiImageContentType(out uint arg0, Span<sbyte> arg1, AsyncData arg2);
        Result SynchronizeParentalControlSettingsAsync(out AsyncData asyncData, out int arg1);
        Result FinishSynchronizeParentalControlSettings(AsyncData asyncData);
        Result FinishSynchronizeParentalControlSettingsWithLastUpdated(out PosixTime posixTime, AsyncData asyncData);
        Result RequestUpdateExemptionListAsync(out AsyncData asyncData, out int arg1, ApplicationId applicationId, bool arg3);
    }
}
