namespace Ryujinx.HLE.HOS.Kernel.Memory
{
    enum DeviceName
    {
        Afi        = 0,
        Avpc       = 1,
        Dc         = 2,
        DcB        = 3,
        Hc         = 4,
        Hda        = 5,
        Isp2       = 6,
        Msencnvenc = 7,
        Nv         = 8,
        Nv2        = 9,
        Ppcs       = 10,
        Sata       = 11,
        Vi         = 12,
        Vic        = 13,
        XusbHost   = 14,
        XusbDev    = 15,
        Tsec       = 16,
        Ppcs1      = 17,
        Dc1        = 18,
        Sdmmc1A    = 19,
        Sdmmc2A    = 20,
        Sdmmc3A    = 21,
        Sdmmc4A    = 22,
        Isp2B      = 23,
        Gpu        = 24,
        GpuB       = 25,
        Ppcs2      = 26,
        Nvdec      = 27,
        Ape        = 28,
        Se         = 29,
        Nvjpg      = 30,
        Hc1        = 31,
        Se1        = 32,
        Axiap      = 33,
        Etr        = 34,
        TsecB      = 35,
        Tsec1      = 36,
        TsecB1     = 37,
        Nvdec1     = 38
    }
}