namespace Ryujinx.HLE.Utilities
{
    internal enum LinuxError
    {
        Success         = 0,
        Eperm           = 1       /* Operation not permitted */,
        Enoent          = 2       /* No such file or directory */,
        Esrch           = 3       /* No such process */,
        Eintr           = 4       /* Interrupted system call */,
        Eio             = 5       /* I/O error */,
        Enxio           = 6       /* No such device or address */,
        E2Big           = 7       /* Argument list too long */,
        Enoexec         = 8       /* Exec format error */,
        Ebadf           = 9       /* Bad file number */,
        Echild          = 10      /* No child processes */,
        Eagain          = 11      /* Try again */,
        Enomem          = 12      /* Out of memory */,
        Eacces          = 13      /* Permission denied */,
        Efault          = 14      /* Bad address */,
        Enotblk         = 15      /* Block device required */,
        Ebusy           = 16      /* Device or resource busy */,
        Eexist          = 17      /* File exists */,
        Exdev           = 18      /* Cross-device link */,
        Enodev          = 19      /* No such device */,
        Enotdir         = 20      /* Not a directory */,
        Eisdir          = 21      /* Is a directory */,
        Einval          = 22      /* Invalid argument */,
        Enfile          = 23      /* File table overflow */,
        Emfile          = 24      /* Too many open files */,
        Enotty          = 25      /* Not a typewriter */,
        Etxtbsy         = 26      /* Text file busy */,
        Efbig           = 27      /* File too large */,
        Enospc          = 28      /* No space left on device */,
        Espipe          = 29      /* Illegal seek */,
        Erofs           = 30      /* Read-only file system */,
        Emlink          = 31      /* Too many links */,
        Epipe           = 32      /* Broken pipe */,
        Edom            = 33      /* Math argument out of domain of func */,
        Erange          = 34      /* Math result not representable */,
        Edeadlk         = 35      /* Resource deadlock would occur */,
        Enametoolong    = 36      /* File name too long */,
        Enolck          = 37      /* No record locks available */,

        /*
         * This error code is special: arch syscall entry code will return
         * -ENOSYS if users try to call a syscall that doesn't exist.  To keep
         * failures of syscalls that really do exist distinguishable from
         * failures due to attempts to use a nonexistent syscall, syscall
         * implementations should refrain from returning -ENOSYS.
         */
        Enosys          = 38      /* Invalid system call number */,
        Enotempty       = 39      /* Directory not empty */,
        Eloop           = 40      /* Too many symbolic links encountered */,
        Ewouldblock     = Eagain  /* Operation would block */,
        Enomsg          = 42      /* No message of desired type */,
        Eidrm           = 43      /* Identifier removed */,
        Echrng          = 44      /* Channel number out of range */,
        El2Nsync        = 45      /* Level 2 not synchronized */,
        El3Hlt          = 46      /* Level 3 halted */,
        El3Rst          = 47      /* Level 3 reset */,
        Elnrng          = 48      /* Link number out of range */,
        Eunatch         = 49      /* Protocol driver not attached */,
        Enocsi          = 50      /* No CSI structure available */,
        El2Hlt          = 51      /* Level 2 halted */,
        Ebade           = 52      /* Invalid exchange */,
        Ebadr           = 53      /* Invalid request descriptor */,
        Exfull          = 54      /* Exchange full */,
        Enoano          = 55      /* No anode */,
        Ebadrqc         = 56      /* Invalid request code */,
        Ebadslt         = 57      /* Invalid slot */,
        Edeadlock       = Edeadlk,
        Ebfont          = 59      /* Bad font file format */,
        Enostr          = 60      /* Device not a stream */,
        Enodata         = 61      /* No data available */,
        Etime           = 62      /* Timer expired */,
        Enosr           = 63      /* Out of streams resources */,
        Enonet          = 64      /* Machine is not on the network */,
        Enopkg          = 65      /* Package not installed */,
        Eremote         = 66      /* Object is remote */,
        Enolink         = 67      /* Link has been severed */,
        Eadv            = 68      /* Advertise error */,
        Esrmnt          = 69      /* Srmount error */,
        Ecomm           = 70      /* Communication error on send */,
        Eproto          = 71      /* Protocol error */,
        Emultihop       = 72      /* Multihop attempted */,
        Edotdot         = 73      /* RFS specific error */,
        Ebadmsg         = 74      /* Not a data message */,
        Eoverflow       = 75      /* Value too large for defined data type */,
        Enotuniq        = 76      /* Name not unique on network */,
        Ebadfd          = 77      /* File descriptor in bad state */,
        Eremchg         = 78      /* Remote address changed */,
        Elibacc         = 79      /* Can not access a needed shared library */,
        Elibbad         = 80      /* Accessing a corrupted shared library */,
        Elibscn         = 81      /* .lib section in a.out corrupted */,
        Elibmax         = 82      /* Attempting to link in too many shared libraries */,
        Elibexec        = 83      /* Cannot exec a shared library directly */,
        Eilseq          = 84      /* Illegal byte sequence */,
        Erestart        = 85      /* Interrupted system call should be restarted */,
        Estrpipe        = 86      /* Streams pipe error */,
        Eusers          = 87      /* Too many users */,
        Enotsock        = 88      /* Socket operation on non-socket */,
        Edestaddrreq    = 89      /* Destination address required */,
        Emsgsize        = 90      /* Message too long */,
        Eprototype      = 91      /* Protocol wrong type for socket */,
        Enoprotoopt     = 92      /* Protocol not available */,
        Eprotonosupport = 93      /* Protocol not supported */,
        Esocktnosupport = 94      /* Socket type not supported */,
        Eopnotsupp      = 95      /* Operation not supported on transport endpoint */,
        Epfnosupport    = 96      /* Protocol family not supported */,
        Eafnosupport    = 97      /* Address family not supported by protocol */,
        Eaddrinuse      = 98      /* Address already in use */,
        Eaddrnotavail   = 99      /* Cannot assign requested address */,
        Enetdown        = 100     /* Network is down */,
        Enetunreach     = 101     /* Network is unreachable */,
        Enetreset       = 102     /* Network dropped connection because of reset */,
        Econnaborted    = 103     /* Software caused connection abort */,
        Econnreset      = 104     /* Connection reset by peer */,
        Enobufs         = 105     /* No buffer space available */,
        Eisconn         = 106     /* Transport endpoint is already connected */,
        Enotconn        = 107     /* Transport endpoint is not connected */,
        Eshutdown       = 108     /* Cannot send after transport endpoint shutdown */,
        Etoomanyrefs    = 109     /* Too many references: cannot splice */,
        Etimedout       = 110     /* Connection timed out */,
        Econnrefused    = 111     /* Connection refused */,
        Ehostdown       = 112     /* Host is down */,
        Ehostunreach    = 113     /* No route to host */,
        Ealready        = 114     /* Operation already in progress */,
        Einprogress     = 115     /* Operation now in progress */,
        Estale          = 116     /* Stale file handle */,
        Euclean         = 117     /* Structure needs cleaning */,
        Enotnam         = 118     /* Not a XENIX named type file */,
        Enavail         = 119     /* No XENIX semaphores available */,
        Eisnam          = 120     /* Is a named type file */,
        Eremoteio       = 121     /* Remote I/O error */,
        Edquot          = 122     /* Quota exceeded */,
        Enomedium       = 123     /* No medium found */,
        Emediumtype     = 124     /* Wrong medium type */,
        Ecanceled       = 125     /* Operation Canceled */,
        Enokey          = 126     /* Required key not available */,
        Ekeyexpired     = 127     /* Key has expired */,
        Ekeyrevoked     = 128     /* Key has been revoked */,
        Ekeyrejected    = 129     /* Key was rejected by service */,

        /* for robust mutexes */
        Eownerdead      = 130     /* Owner died */,
        Enotrecoverable = 131     /* State not recoverable */,

        Erfkill         = 132     /* Operation not possible due to RF-kill */,

        Ehwpoison       = 133     /* Memory page has hardware error */,
    }
}